# Generated by Django 3.2.7 on 2023-02-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightPlan',
            fields=[
                ('FlightPlanId', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
    ]
